### ISSUE TITLE
Generated sensu client /etc/default/sensu configuration paramters are bad

### ISSUE THREAD

**Issue by ghost** [hybridindie/sensu-docker#2]
Getting errors when I start the sensu client.  The install script needs to remove the double quotes around the 2 configuration parameters in /etc/default/sensu and make sure they both start in column 1.

/etc/init.d/sensu-client restart

/etc/default/sensu: line 1: EMBEDDED_RUBY=true: command not found
/etc/default/sensu: line 2: LOG_LEVEL=info: command not found

**Comment by hybridindie** [comment]
Fixed in new release
